<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>comment</key>
    <string>Inherits rules from free form Fortran.</string>
    <key>name</key>
    <string>Fortran - Fixed Form</string>
    <key>scopeName</key>
    <string>source.fortran.fixed</string>
    <key>fileTypes</key>
    <array>
      <string>f</string>
      <string>F</string>
      <string>f77</string>
      <string>F77</string>
      <string>for</string>
      <string>FOR</string>
      <string>fpp</string>
      <string>FPP</string>
    </array>
    <key>injections</key>
    <dict>
      <key>source.fortran.fixed - ( string | comment )</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#line-header</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#line-end-comment</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#line-header</string>
      </dict>
      <dict>
        <key>include</key>
        <string>source.fortran.free</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.line.fortran</string>
            <key>begin</key>
            <string>^[cC\*]</string>
            <key>end</key>
            <string>\n</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.line.fortran</string>
            <key>begin</key>
            <string>^ *!</string>
            <key>end</key>
            <string>\n</string>
          </dict>
        </array>
      </dict>
      <key>line-end-comment</key>
      <dict>
        <key>name</key>
        <string>comment.line-end.fortran</string>
        <key>begin</key>
        <string>(?&lt;=^.{72})(?!\n)</string>
        <key>end</key>
        <string>(?=\n)</string>
      </dict>
      <key>line-header</key>
      <dict>
        <key>match</key>
        <string>^(?!\s*[!#])(?:([ \d]{5} )|( {5}.)|(.{1,5}))</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.fortran</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.line-continuation-operator.fortran</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>invalid.error.fortran</string>
          </dict>
        </dict>
      </dict>
    </dict>
  </dict>
</plist>